refactor(Pipeline): Deploy to Ms. App Center

diff --git a/.github/workflows/flutter_streamlined_cicd_pipeline.yml b/.github/workflows/flutter_streamlined_cicd_pipeline.yml
--- a/.github/workflows/flutter_streamlined_cicd_pipeline.yml
+++ b/.github/workflows/flutter_streamlined_cicd_pipeline.yml
@@ -30,41 +30,7 @@ jobs:
       uses: actions/upload-artifact@v2
       with:
         name: android-release
-        path: build/app/outputs/flutter-apk/android-release.apk
-
-  # build-ios:
-  #   name: Build iOS
-  #   runs-on: macos-latest
-
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
-
-  #     - name: Set up Java
-  #       uses: actions/setup-java@v3
-  #       with:
-  #         distribution: 'adopt'
-  #         java-version: '17.x'
-
-  #     - name: Set up Flutter
-  #       uses: subosito/flutter-action@v2
-  #       with:
-  #         flutter-version: '3.22.2' # specify the correct version
-
-  #     - run: |
-  #         flutter build ios --no-codesign
-  #         cd build/ios/iphoneos
-  #         mkdir Payload
-  #         cd Payload
-  #         ln -s ../Runner.app
-  #         cd ..
-  #         zip -r app.ipa Payload
-
-  #     - name: Upload iOS Artifact
-  #       uses: actions/upload-artifact@v2
-  #       with:
-  #         name: ios-release.ipa
-  #         path: build/ios/iphoneos/*.ipa
+        path: build/app/outputs/flutter-apk/app-release.apk
 
   deploy:
     name: Deploy to App Center
@@ -72,28 +38,128 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
     - name: Download Android Artifact
       uses: actions/download-artifact@v2
       with:
         name: android-release
         path: android-release.apk
 
-    # - name: Download iOS Artifact
-    #   uses: actions/download-artifact@v2
-    #   with:
-    #     name: ios-release.ipa
+    - name: Verify Android Artifact
+      run: ls -l android-release.apk
 
     - name: Deploy Android to App Center
       run: |
         if [ -f "android-release.apk" ]; then
-        curl -F "ipa=@android-release.apk" \
-          -H "X-API-Token: ${{ secrets.APPCENTER_TOKEN }}" \
-          -H "Accept: application/json" \
-          "https://api.appcenter.ms/v0.1/apps/vanda-cloud/vanda-cloud-1/release_uploads"
+          curl -F "ipa=@android-release.apk" \
+            -H "X-API-Token: ${{ secrets.APPCENTER_TOKEN }}" \
+            -H "Accept: application/json" \
+            "https://api.appcenter.ms/v0.1/apps/vanda-cloud/vanda-cloud-1/release_uploads"
         else
           echo "Android APK not found!"
           exit 1
         fi
+
+
+
+# name: Flutter » Streamlined CI/CD Pipeline
+# run-name: ${{ github.actor }} is publishing (${{ github.ref_name }}) 🚀
+
+# on:
+#   push:
+#     branches:
+#       - dev
+
+# jobs:
+#   build-android:
+#     name: Build Android
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Checkout repository
+#       uses: actions/checkout@v2
+
+#     - name: Set up Flutter
+#       uses: subosito/flutter-action@v2
+#       with:
+#         flutter-version: '3.22.2'  # Use your desired Flutter version
+
+#     - name: Install dependencies
+#       run: flutter pub get
+
+#     - name: Build APK
+#       run: flutter build apk --release
+
+#     - name: Upload Android Artifact
+#       uses: actions/upload-artifact@v2
+#       with:
+#         name: android-release
+#         path: build/app/outputs/flutter-apk/android-release.apk
+
+#   # build-ios:
+#   #   name: Build iOS
+#   #   runs-on: macos-latest
+
+#   #   steps:
+#   #     - name: Checkout repository
+#   #       uses: actions/checkout@v3
+
+#   #     - name: Set up Java
+#   #       uses: actions/setup-java@v3
+#   #       with:
+#   #         distribution: 'adopt'
+#   #         java-version: '17.x'
+
+#   #     - name: Set up Flutter
+#   #       uses: subosito/flutter-action@v2
+#   #       with:
+#   #         flutter-version: '3.22.2' # specify the correct version
+
+#   #     - run: |
+#   #         flutter build ios --no-codesign
+#   #         cd build/ios/iphoneos
+#   #         mkdir Payload
+#   #         cd Payload
+#   #         ln -s ../Runner.app
+#   #         cd ..
+#   #         zip -r app.ipa Payload
+
+#   #     - name: Upload iOS Artifact
+#   #       uses: actions/upload-artifact@v2
+#   #       with:
+#   #         name: ios-release.ipa
+#   #         path: build/ios/iphoneos/*.ipa
+
+#   deploy:
+#     name: Deploy to App Center
+#     needs: [build-android]
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Download Android Artifact
+#       uses: actions/download-artifact@v2
+#       with:
+#         name: android-release
+#         path: android-release.apk
+
+#     # - name: Download iOS Artifact
+#     #   uses: actions/download-artifact@v2
+#     #   with:
+#     #     name: ios-release.ipa
+
+#     - name: Deploy Android to App Center
+#       run: |
+#         if [ -f "android-release.apk" ]; then
+#         curl -F "ipa=@android-release.apk" \
+#           -H "X-API-Token: ${{ secrets.APPCENTER_TOKEN }}" \
+#           -H "Accept: application/json" \
+#           "https://api.appcenter.ms/v0.1/apps/vanda-cloud/vanda-cloud-1/release_uploads"
+#         else
+#           echo "Android APK not found!"
+#           exit 1
+#         fi
 
     # - name: Deploy iOS to App Center
     #   run: |
